In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import torch

import promovits

In [37]:
a = torch.ones(4, dtype=torch.float, requires_grad=True)[None, None]
b = torch.ones(16, dtype=torch.float, requires_grad=True)[None, None]
a.retain_grad()
b.retain_grad()

In [36]:
c = torch.nn.functional.conv1d(a, b, padding=2)

In [37]:
c

tensor([[[ 1.,  2.,  2., -2., -3.]]], grad_fn=<SqueezeBackward1>)

In [38]:
torch.nn.functional.conv_transpose1d(c, b, padding=2)

tensor([[[-1.,  4.,  5.]]], grad_fn=<SqueezeBackward1>)

In [3]:
causal_conv = promovits.model.modules.CausalConv1d(1, 1, 3, bias=False)
causal_conv.weight = torch.nn.Parameter(b)
d = causal_conv(a)
d.retain_grad()
d

tensor([[[1., 2., 3.]]], grad_fn=<SliceBackward0>)

In [4]:
d.backward(gradient=torch.ones_like(d))

In [5]:
a.grad

tensor([[[3., 2., 1.]]])

In [14]:
a = torch.ones(4, dtype=torch.float)[None, None]
b = torch.ones(4, dtype=torch.float)[None, None]
causal_transpose = promovits.model.modules.CausalTransposeConv1d(
    1,
    1,
    b.shape[2],
    padding=0,
    stride=1,
    bias=False)
causal_transpose.weight = torch.nn.Parameter(b)
causal_transpose(a)

3


tensor([[[1., 2., 3., 4.]]], grad_fn=<SliceBackward0>)